### ISSUE TITLE
Proč je tohle

### ISSUE THREAD

**Issue by hernikplays** [gumernus/spizecek#1]
```js
if(message.author.tag === client.user.tag){
```
jestli tohle má kontrolovat, jestli je uživatel bot, proč nepoužít [`message.author.bot`](https://discord.js.org/#/docs/main/stable/class/User)

**Comment by Atsukoro1** [comment]
Protože jsem kokot

**Comment by gumernus** [comment]
to je aby bot neodpovídal sám na sebe xd

**Comment by hernikplays** [comment]
proč nepoužít [`message.author.bot`](https://discord.js.org/#/docs/main/stable/class/User)

**Comment by gumernus** [comment]
@hernikplays ano taky mě to ve vaně napadlo
